"""empty message

Revision ID: 35187062ea4e
Revises: d06242b7fd3c
Create Date: 2025-09-19 13:39:02.473921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35187062ea4e'
down_revision = 'd06242b7fd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('degree', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('resume_file')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('degree')
        batch_op.drop_column('year')
        batch_op.drop_column('college')

    # ### end Alembic commands ###
