"""empty message

Revision ID: 404ee1e7e721
Revises: 6fd24794c177
Create Date: 2025-09-22 11:39:28.650292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404ee1e7e721'
down_revision = '6fd24794c177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified', sa.Boolean(), nullable=True, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('notified')

    # ### end Alembic commands ###
