"""empty message

Revision ID: 72fdf87157e7
Revises: a27b6fe30234
Create Date: 2025-09-26 19:07:43.410283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fdf87157e7'
down_revision = 'a27b6fe30234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathon_post', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathon_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=300), nullable=False))

    # ### end Alembic commands ###
