"""Add male_slots and female_slots to Post

Revision ID: 769d1649de71
Revises: f679391338bb
Create Date: 2025-09-20 14:10:08.971207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769d1649de71'
down_revision = 'f679391338bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('male_slots', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('female_slots', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('female_slots')
        batch_op.drop_column('male_slots')

    # ### end Alembic commands ###
