"""empty message

Revision ID: 8e735e4e27c2
Revises: a42186fb2a24
Create Date: 2025-09-20 18:33:05.542978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e735e4e27c2'
down_revision = 'a42186fb2a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_read_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('last_read', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_read_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_read_status_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_read_status_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_read_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_read_status_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_read_status_post_id'))

    op.drop_table('chat_read_status')
    # ### end Alembic commands ###
