"""empty message

Revision ID: a27b6fe30234
Revises: 3adfa6066537
Create Date: 2025-09-26 18:58:45.226595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27b6fe30234'
down_revision = '3adfa6066537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('hackathon_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hackathon_post_date_posted'), ['date_posted'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('event_venue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_venue', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('hackathon_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hackathon_post_date_posted'))

    op.drop_table('hackathon_post')
    # ### end Alembic commands ###
