"""empty message

Revision ID: c7f91c2e4b84
Revises: 35187062ea4e
Create Date: 2025-09-19 14:12:14.761595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f91c2e4b84'
down_revision = '35187062ea4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_requirement', sa.String(length=20), nullable=True))

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('gender_requirement')

    # ### end Alembic commands ###
