"""empty message

Revision ID: d06242b7fd3c
Revises: 462ea0688856
Create Date: 2025-09-19 13:31:52.967138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06242b7fd3c'
down_revision = '462ea0688856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('idea', sa.Text(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('team_requirement', sa.String(length=100), nullable=True),
    sa.Column('event_poster_filename', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_datetime', sa.DateTime(), nullable=True),
    sa.Column('event_venue', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_timestamp'), ['timestamp'], unique=False)

    op.create_table('post_required_skills',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'skill_id')
    )
    op.create_table('post_teammates',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('resume_file')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('degree')
        batch_op.drop_column('github_url')
        batch_op.drop_column('year')
        batch_op.drop_column('college')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('college', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('year', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('degree', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_file', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('post_teammates')
    op.drop_table('post_required_skills')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_timestamp'))
        batch_op.drop_index(batch_op.f('ix_application_post_id'))
        batch_op.drop_index(batch_op.f('ix_application_applicant_id'))

    op.drop_table('application')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_index(batch_op.f('ix_post_creator_id'))

    op.drop_table('post')
    # ### end Alembic commands ###
