"""empty message

Revision ID: e048215f61e1
Revises: 72fdf87157e7
Create Date: 2025-09-26 22:08:03.358135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e048215f61e1'
down_revision = '72fdf87157e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackathon_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hackathon_post_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hackathon_post_id'], ['hackathon_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hackathon_team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hackathon_team_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hackathon_team_hackathon_post_id'), ['hackathon_post_id'], unique=False)

    op.create_table('hackathon_team_members',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['hackathon_team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    with op.batch_alter_table('hackathon_post', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathon_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('hackathon_team_members')
    with op.batch_alter_table('hackathon_team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hackathon_team_hackathon_post_id'))
        batch_op.drop_index(batch_op.f('ix_hackathon_team_creator_id'))

    op.drop_table('hackathon_team')
    # ### end Alembic commands ###
